### PR TITLE
feat: Add slide-in animation for session list panel in AppWindow

### PR DESCRIPTION
**Pull request by JonathanCosta**
### Overview
This PR introduces a sliding animation feature for the session list panel in the `AppWindow` component, enhancing the user interface and experience by allowing users to toggle the visibility of the panel dynamically.

### Changes:
- **Sliding Animation**: A new method, `slideSessionListPanel`, implements a smooth slide-in/slide-out animation for the session list panel using a `Timer`.
- **Visibility Toggle**: Added a `panelVisible` boolean to track the panel’s visibility state and manage the animation flow.
- **UI Adjustments**: 
  - A new toggle button (`btnList`) is added to the session panel to trigger the sliding action.
  - Adjusted the layout and dimensions of session panel components for better alignment and usability.
- **Code Cleanup**: Removed some unused/commented-out code to keep the component clean and maintainable.

### Motivation:
This feature improves the user experience by making the session list panel more accessible without taking up constant screen space, adding a modern touch to the UI.

### How to test:
1. Open the `AppWindow`.
2. Click the new toggle button to slide the session list panel in and out.
3. Ensure the panel visibility is smoothly animated and the UI remains responsive during the transition.

### CODE REVIEW

**Comment by achikoko** [comment]
Hi Jonathan, thank you for your pull request. I reviewed it and I think it's a good idea, but there is a couple of things that I don't fully like. You are saving space on the left but adding it on top... I'd prefer it rather on the left than the top. 
image
I don't fully see how we can fix it, but I propose something like this. Moving the "configuration" button to the bottom status bar. And close the left panel not fully but until one button fits. Then we could implement some kind of mini SessionListPanel to fit in there, what do you think? Then I would prefer the "add" button to stay where it always has been, for the habits.. :)  (we can parametrize it into a setting to avoid conflicts haha)

**Comment by JonathanCosta** [comment]
Hi,

Thank you for the thorough review and feedback! I like the project, whenever i can i try to adjust something. I don't have a command of Java, in fact I work with PHP, so I'm not sure if I can implement this in the best way.

I see your point about preferring the left side space over adding extra space on top. Your proposal makes a lot of sense to me, and I like the idea of moving the "configuration" button to the bottom status bar.

Regarding the SessionListPanel, I think your suggestion of minimizing it to one button width and introducing a mini version of it could work well to maintain functionality without taking too much horizontal space. 

image2
www.photopea.com/#itQuTCgbi

is a rough sketch of the adjustments I have in mind based on your suggestions.
Let me know if this direction works for you!

**Comment by achikoko** [comment]
That's exactly what I was thinking on!! It would be perfect to reflect your original PR intention. If you are on the mood, try to implement it! If there is any trouble, I can merge the PR and try to fix it.

I like this app too. I use it nearly every day but I don't have so much time to dedicate to it. Now I'm trying to fix the issues with zombie connections and dead forwarded ports after suspending the pc. I'll make it to detect better that situations and ask the user to reconnect. I also want to remove support for any language but English (as any IDE or development tool which only supports one language).

**Comment by achikoko** [comment]
I think I can fix it myself. I've been refactoring and stabilizing the code much more and I also would like to have this feature for the next release ;) Thank you!

**Pull request merged**
